### ISSUE TITLE
realy bad

### ISSUE THREAD

**Issue by ghost** [j4cobgarby/Cordial2#14]
realy bad coded like you are coding almost everyting in the routes file and you are using raw queries instead of [Eloquent](https://laravel.com/docs/5.4/eloquent)

you should learn laravel before starting to code

**Comment by j4cobgarby** [comment]
Seriously? I don't know if you realise this but this project was intended as _a way_ of learning Laravel.

And you know what else is really bad? Your spelling, grammar, and attitude.

And no I'm not coding everything in the routes file - much of the application's logic uses controllers, and a great deal of it also uses helper functions.

One more thing: **how on earth would I "learn laravel before [...] starting to code"?** That simply doesn't make sense. The best (only?) way to learn Laravel is to write something in it.

I see very little point in you creating this issue on my repository (which by the way isn't even an issue.) If you don't like my repository great - leave. I would very much appreciate that. There's no reason whatsoever to create such an _Issue_.
